# Generated by Django 5.0.1 on 2024-02-01 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmpname', models.CharField(max_length=200, unique=True)),
                ('empname', models.CharField(max_length=200)),
                ('empQuali', models.CharField(max_length=200)),
                ('empDept', models.CharField(max_length=200)),
                ('empDsg', models.CharField(max_length=200)),
                ('empImg', models.ImageField(blank=True, default='default.jpg', upload_to='images')),
                ('empJdate', models.DateField()),
                ('empSalary', models.IntegerField()),
                ('empPhone', models.IntegerField()),
            ],
        ),
    ]
