# Generated by Django 5.0.1 on 2024-02-19 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='empImg',
            field=models.ImageField(blank=True, default='images/default.jpg', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='company',
            name='empJdate',
            field=models.DateTimeField(),
        ),
    ]
